server:
  port: 20050
  servlet:
    context-path: /file

spring:
  application:
    name: easychat-clone-filesystem-service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: hongkong
        namespace: dc5be15a-eded-46f9-a020-08c42359aab3
        group: org.example
minio:
  endpoint: "http://localhost:9000"
  accessKey: "xiaojie"
  secretKey: "xiaojie"
  bucketName: "easychat"